/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.io.IOException;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import parser.Article;
import system.WallStreetSystem;

/**
 * 
 * @author Fiona
 */

public class SearchFrame extends javax.swing.JFrame {

	private List<Article> articles = null;
	private WallStreetSystem system = null;

	/**
	 * Creates new form SearchFrame
	 */
	public SearchFrame() {
		initComponents();
		viewPanel.setVisible(false);
		system = new WallStreetSystem();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		searchGroup = new javax.swing.ButtonGroup();
		searchPanel = new javax.swing.JPanel();
		searchField = new javax.swing.JTextField();
		searchButton = new javax.swing.JButton();
		titleLabel = new javax.swing.JLabel();
		simpleRadio = new javax.swing.JRadioButton();
		advRadio = new javax.swing.JRadioButton();
		docViewButton = new javax.swing.JButton();
		viewPanel = new javax.swing.JPanel();
		textScroll = new javax.swing.JScrollPane();
		docPane = new javax.swing.JTextPane();
		docTitle = new javax.swing.JLabel();
		resultsLabel = new javax.swing.JLabel();
		treeScroll = new javax.swing.JScrollPane();
		docTree = new javax.swing.JTree();
		searchViewButton = new javax.swing.JButton();
		searchBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		exitItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Wall Street Journal Viewer");
		setMinimumSize(new java.awt.Dimension(480, 360));
		setName("mainFrame"); // NOI18N

		searchPanel.setName("searchPanel"); // NOI18N
		searchPanel.setPreferredSize(new java.awt.Dimension(800, 600));

		searchField.setName("searchField"); // NOI18N
		searchField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchFieldActionPerformed(evt);
			}
		});

		searchButton.setLabel("Search");
		searchButton.setName("searchButton"); // NOI18N
		searchButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					searchButtonActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		titleLabel.setText("Wall Street Journal Viewer");

		searchGroup.add(simpleRadio);
		simpleRadio.setText("Simple Search");
		simpleRadio.setName("simpleRadio"); // NOI18N

		searchGroup.add(advRadio);
		advRadio.setText("Advanced Search");
		advRadio.setName("advRadio"); // NOI18N

		docViewButton.setText("Document Viewer");
		docViewButton.setName("docViewButton"); // NOI18N

		javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(
				searchPanel);
		searchPanel.setLayout(searchPanelLayout);
		searchPanelLayout
				.setHorizontalGroup(searchPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								searchPanelLayout
										.createSequentialGroup()
										.addGap(44, 44, 44)
										.addGroup(
												searchPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																searchPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				simpleRadio)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				advRadio))
														.addComponent(
																titleLabel))
										.addContainerGap(301, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								searchPanelLayout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(docViewButton)
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								searchPanelLayout
										.createSequentialGroup()
										.addGap(32, 32, 32)
										.addComponent(
												searchField,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												337,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(searchButton)
										.addGap(90, 90, 90)));
		searchPanelLayout
				.setVerticalGroup(searchPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								searchPanelLayout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addComponent(
												titleLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												54,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(49, 49, 49)
										.addGroup(
												searchPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																searchButton)
														.addComponent(
																searchField,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												searchPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																simpleRadio)
														.addComponent(advRadio))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												131, Short.MAX_VALUE)
										.addComponent(docViewButton)
										.addContainerGap()));

		searchButton.getAccessibleContext().setAccessibleDescription("");

		viewPanel.setName("viewPanel"); // NOI18N
		viewPanel.setPreferredSize(new java.awt.Dimension(480, 340));

		textScroll.setName("textScroll"); // NOI18N

		docPane.setEnabled(true);
		docPane.setEditable(false);
		docPane.setSelectionColor(new java.awt.Color(204, 204, 204));
		textScroll.setViewportView(docPane);

		docTitle.setText("Document Viewer");

		resultsLabel.setText("Results");

		treeScroll.setName("treeScroll"); // NOI18N

		javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode(
				"Wall Street Articles");
		docTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		docTree.setName("docTree"); // NOI18N
		docTree.setRowHeight(14);
		docTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
			public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
				docTreeValueChanged(evt);
			}
		});
		treeScroll.setViewportView(docTree);
		docTree.getAccessibleContext().setAccessibleName("docTree");

		searchViewButton.setText("Search Page");
		searchViewButton.setToolTipText("Return to Search Page");
		searchViewButton.setName("searchViewButton"); // NOI18N
		searchViewButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchViewButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout viewPanelLayout = new javax.swing.GroupLayout(
				viewPanel);
		viewPanel.setLayout(viewPanelLayout);
		viewPanelLayout
				.setHorizontalGroup(viewPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								viewPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												viewPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																viewPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				treeScroll,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				244,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				textScroll,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				346,
																				Short.MAX_VALUE))
														.addGroup(
																viewPanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				resultsLabel,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				244,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				docTitle,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				346,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																viewPanelLayout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				searchViewButton)))
										.addContainerGap()));
		viewPanelLayout
				.setVerticalGroup(viewPanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								viewPanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												viewPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																resultsLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																docTitle,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												viewPanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																treeScroll,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																textScroll,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																284,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(searchViewButton)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		searchBar.setName("searchBar"); // NOI18N

		fileMenu.setText("File");
		fileMenu.setName("fileMenu"); // NOI18N

		exitItem.setText("Exit");
		exitItem.setName("exitItem"); // NOI18N
		exitItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitItem);

		searchBar.add(fileMenu);

		setJMenuBar(searchBar);
		searchBar.getAccessibleContext().setAccessibleName("searchMenu");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(searchPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, 608,
						Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(viewPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										608, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(searchPanel,
						javax.swing.GroupLayout.DEFAULT_SIZE, 381,
						Short.MAX_VALUE)
				.addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(viewPanel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										381, Short.MAX_VALUE)));

		getAccessibleContext().setAccessibleDescription("");

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchFieldActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_searchFieldActionPerformed

	private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exitItemActionPerformed
		int result = JOptionPane.showConfirmDialog(this,
				"Are you sure you wish to exit?", "Exit",
				JOptionPane.WARNING_MESSAGE, JOptionPane.OK_OPTION);
		if (result == 0) {
			System.exit(0);
		}
	}// GEN-LAST:event_exitItemActionPerformed

	private void searchViewButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchViewButtonActionPerformed
		// TODO add your handling code here:
		searchPanel.setVisible(true);
		viewPanel.setVisible(false);
		docPane.setText("");
	}// GEN-LAST:event_searchViewButtonActionPerformed

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt)
			throws IOException {// GEN-FIRST:event_searchButtonActionPerformed
		if (searchField.getText().length() < 2) {
			JOptionPane.showConfirmDialog(this,
					"You must enter a valid query to be able to perform a search.",
					"Search", JOptionPane.WARNING_MESSAGE,
					JOptionPane.OK_OPTION);
			searchField.setText("");
		} else {
			String[] fields = {"body", "leadPar", "in"};
			system.search(searchField.getText(), fields);
			articles = system.getResults();
			this.populateTree();
			searchPanel.setVisible(false);
			viewPanel.setVisible(true);
		}
	}// GEN-LAST:event_searchButtonActionPerformed

	private void docTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {// GEN-FIRST:event_docTreeValueChanged

		String node = evt.getNewLeadSelectionPath().getLastPathComponent()
				.toString();
		for(int i = 0; i < articles.size(); i++) {
			if(articles.get(i).getDocNo().equalsIgnoreCase(node)) {
				docPane.setText(articles.get(i).printAll());
				break;
			}
		}
		

		docPane.updateUI();
	}// GEN-LAST:event_docTreeValueChanged

	private void populateTree() {
		DefaultMutableTreeNode node = buildNodeFromString();
		DefaultTreeModel model = new DefaultTreeModel(node);
		docTree.setModel(model);
	}

	private DefaultMutableTreeNode buildNodeFromString() {
		DefaultMutableTreeNode node = null, root = null;
		root = new DefaultMutableTreeNode("Search: " + searchField.getText());
		
		for (Article key : articles) {
			node = new DefaultMutableTreeNode(key.getDocNo());
			root.add(node);
		}
		return root;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SearchFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SearchFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SearchFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SearchFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SearchFrame().setVisible(true);
			}
		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JRadioButton advRadio;
	private javax.swing.JTextPane docPane;
	private javax.swing.JLabel docTitle;
	private javax.swing.JTree docTree;
	private javax.swing.JButton docViewButton;
	private javax.swing.JMenuItem exitItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JLabel resultsLabel;
	private javax.swing.JMenuBar searchBar;
	private javax.swing.JButton searchButton;
	private javax.swing.JTextField searchField;
	private javax.swing.ButtonGroup searchGroup;
	private javax.swing.JPanel searchPanel;
	private javax.swing.JButton searchViewButton;
	private javax.swing.JRadioButton simpleRadio;
	private javax.swing.JScrollPane textScroll;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JScrollPane treeScroll;
	private javax.swing.JPanel viewPanel;
	// End of variables declaration//GEN-END:variables
}
